# SERVER
spring.application.name=E-Learning Platform
server.port=8081

# ✅ Context path remove karo ya blank rakho
server.servlet.context-path=/

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/elearning_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=true

# ✅ JSP VIEW RESOLVER
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.registered=true
spring.mvc.static-path-pattern=/static/**

# ✅ Thymeleaf BAND karo
spring.thymeleaf.enabled=false

# UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB



# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=collegeboys17112005@gmail.com
spring.mail.password=bysjlyqxodshuabh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CUSTOM
app.base-url=http://localhost:8082
app.upload-dir=uploads/
app.certificate-dir=certificates/
app.email.from=noreply@elearning.com
app.token.expiry.hours=24